package nl.robinlaugs.quotes.data.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Quote")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Quote {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String author;

    @DynamoDBAttribute
    private String quote;

    @DynamoDBAttribute
    private int votes;

    public void upvote() {
        votes++;
    }

    public void downvote() {
        votes--;
    }

}
